name: iconscout_downloader
description: Iconscout 3D illustration, vectors icons, Photos & Images, Video & Audio Downloader without watermark.
version: 0.0.1
repository: https://github.com/thitlwincoder/iconscout_downloader/

environment:
  sdk: ^3.0.5

dependencies:
  http: ^1.1.0
  html: ^0.15.4

dev_dependencies:
  lints: ^2.0.0
